// Copyright 2025 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
// Generated by PeakRDL raw-header

package cheshire_external_addrmap_pkg;

localparam longint unsigned BASE_ADDR = 64'h0;
localparam longint unsigned SIZE = 64'h80800000;

localparam longint unsigned DRAM_BASE_ADDR = 64'h80000000;
localparam longint unsigned DRAM_SIZE = 64'h800000;



endpackage;
