// Copyright 2025 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
// Generated by PeakRDL raw-header

package cheshire_addrmap_pkg;

localparam longint unsigned BASE_ADDR = 64'h0;
localparam longint unsigned SIZE = 64'h80800000;

localparam longint unsigned EXTROM_BASE_ADDR = 64'h0;
localparam longint unsigned EXTROM_SIZE = 64'h40000;

localparam longint unsigned DMA_BASE_ADDR = 64'h1000000;
localparam longint unsigned DMA_SIZE = 64'h1000;

localparam longint unsigned L1_DSPM_BASE_ADDR = 64'h1800000;
localparam longint unsigned L1_DSPM_SIZE = 64'h8000;

localparam longint unsigned L1_ISPM_BASE_ADDR = 64'h1A00000;
localparam longint unsigned L1_ISPM_SIZE = 64'h8000;

localparam longint unsigned BOOTROM_BASE_ADDR = 64'h2000000;
localparam longint unsigned BOOTROM_SIZE = 64'h40000;

localparam longint unsigned CLINT_BASE_ADDR = 64'h2040000;
localparam longint unsigned CLINT_SIZE = 64'h40000;

localparam longint unsigned IRQ_ROUTER_BASE_ADDR = 64'h2080000;
localparam longint unsigned IRQ_ROUTER_SIZE = 64'h40000;

localparam longint unsigned AXIRT_BASE_ADDR = 64'h20C0000;
localparam longint unsigned AXIRT_SIZE = 64'h40000;

localparam longint unsigned REGS_BASE_ADDR = 64'h3000000;
localparam longint unsigned REGS_SIZE = 64'h5C;

localparam longint unsigned LLC_BASE_ADDR = 64'h3001000;
localparam longint unsigned LLC_SIZE = 64'h1000;

localparam longint unsigned UART_BASE_ADDR = 64'h3002000;
localparam longint unsigned UART_SIZE = 64'h1000;

localparam longint unsigned I2C_BASE_ADDR = 64'h3003000;
localparam longint unsigned I2C_SIZE = 64'h1000;

localparam longint unsigned SPIH_BASE_ADDR = 64'h3004000;
localparam longint unsigned SPIH_SIZE = 64'h1000;

localparam longint unsigned GPIO_BASE_ADDR = 64'h3005000;
localparam longint unsigned GPIO_SIZE = 64'h1000;

localparam longint unsigned SLINK_BASE_ADDR = 64'h3006000;
localparam longint unsigned SLINK_SIZE = 64'h804;

localparam longint unsigned VGA_BASE_ADDR = 64'h3007000;
localparam longint unsigned VGA_SIZE = 64'h1000;

localparam longint unsigned USB_BASE_ADDR = 64'h3008000;
localparam longint unsigned USB_SIZE = 64'h1000;

localparam longint unsigned BUS_ERR_BASE_ADDR = 64'h3009000;
localparam longint unsigned BUS_ERR_SIZE = 64'h40;

localparam longint unsigned TAGGER_BASE_ADDR = 64'h300A000;
localparam longint unsigned TAGGER_SIZE = 64'h100;

localparam longint unsigned PLIC_BASE_ADDR = 64'h4000000;
localparam longint unsigned PLIC_SIZE = 64'h4000000;

localparam longint unsigned CLIC_BASE_ADDR = 64'h8000000;
localparam longint unsigned CLIC_SIZE = 64'h40000;

localparam longint unsigned SPM_BASE_ADDR = 64'h10000000;
localparam longint unsigned SPM_SIZE = 64'h10000;

localparam longint unsigned SPM_UNC_BASE_ADDR = 64'h14000000;
localparam longint unsigned SPM_UNC_SIZE = 64'h4000000;

localparam longint unsigned DRAM_BASE_ADDR = 64'h80000000;
localparam longint unsigned DRAM_SIZE = 64'h800000;

localparam longint unsigned DMA_STATUS_BASE_ADDR = 64'h1000000;
localparam longint unsigned DMA__END_BASE_ADDR = 64'h1000FFC;
localparam longint unsigned CLINT_STATUS_BASE_ADDR = 64'h2040000;
localparam longint unsigned CLINT__END_BASE_ADDR = 64'h207FFFC;
localparam longint unsigned IRQ_ROUTER_STATUS_BASE_ADDR = 64'h2080000;
localparam longint unsigned IRQ_ROUTER__END_BASE_ADDR = 64'h20BFFFC;
localparam longint unsigned AXIRT_STATUS_BASE_ADDR = 64'h20C0000;
localparam longint unsigned AXIRT__END_BASE_ADDR = 64'h20FFFFC;
function automatic longint unsigned REGS_SCRATCH_BASE_ADDR(input int unsigned scratch_idx);
    return 64'h3000000 + (scratch_idx * 64'h4);
endfunction
localparam longint unsigned REGS_SCRATCH_NUM = 64'h10;
localparam longint unsigned REGS_BOOT_MODE_BASE_ADDR = 64'h3000040;
localparam longint unsigned REGS_RTC_FREQ_BASE_ADDR = 64'h3000044;
localparam longint unsigned REGS_PLATFORM_ROM_BASE_ADDR = 64'h3000048;
localparam longint unsigned REGS_NUM_INT_HARTS_BASE_ADDR = 64'h300004C;
localparam longint unsigned REGS_HW_FEATURES_BASE_ADDR = 64'h3000050;
localparam longint unsigned REGS_LLC_SIZE_BASE_ADDR = 64'h3000054;
localparam longint unsigned REGS_VGA_PARAMS_BASE_ADDR = 64'h3000058;
localparam longint unsigned LLC_STATUS_BASE_ADDR = 64'h3001000;
localparam longint unsigned LLC__END_BASE_ADDR = 64'h3001FFC;
localparam longint unsigned UART_STATUS_BASE_ADDR = 64'h3002000;
localparam longint unsigned UART__END_BASE_ADDR = 64'h3002FFC;
localparam longint unsigned I2C_STATUS_BASE_ADDR = 64'h3003000;
localparam longint unsigned I2C__END_BASE_ADDR = 64'h3003FFC;
localparam longint unsigned SPIH_STATUS_BASE_ADDR = 64'h3004000;
localparam longint unsigned SPIH__END_BASE_ADDR = 64'h3004FFC;
localparam longint unsigned GPIO_STATUS_BASE_ADDR = 64'h3005000;
localparam longint unsigned GPIO__END_BASE_ADDR = 64'h3005FFC;
localparam longint unsigned SLINK_CTRL_BASE_ADDR = 64'h3006000;
localparam longint unsigned SLINK_ISOLATED_BASE_ADDR = 64'h3006004;
localparam longint unsigned SLINK_RAW_MODE_EN_BASE_ADDR = 64'h3006008;
localparam longint unsigned SLINK_RAW_MODE_IN_DATA_BASE_ADDR = 64'h300600C;
localparam longint unsigned SLINK_RAW_MODE_IN_CH_SEL_BASE_ADDR = 64'h3006010;
localparam longint unsigned SLINK_RAW_MODE_OUT_DATA_FIFO_BASE_ADDR = 64'h3006014;
localparam longint unsigned SLINK_RAW_MODE_OUT_DATA_FIFO_CTRL_BASE_ADDR = 64'h3006018;
localparam longint unsigned SLINK_RAW_MODE_OUT_EN_BASE_ADDR = 64'h300601C;
localparam longint unsigned SLINK_FLOW_CONTROL_FIFO_CLEAR_BASE_ADDR = 64'h3006020;
function automatic longint unsigned SLINK_RAW_MODE_IN_DATA_VALID_BASE_ADDR(input int unsigned raw_mode_in_data_valid_idx);
    return 64'h3006100 + (raw_mode_in_data_valid_idx * 64'h4);
endfunction
localparam longint unsigned SLINK_RAW_MODE_IN_DATA_VALID_NUM = 64'h1;
function automatic longint unsigned SLINK_RAW_MODE_OUT_CH_MASK_BASE_ADDR(input int unsigned raw_mode_out_ch_mask_idx);
    return 64'h3006200 + (raw_mode_out_ch_mask_idx * 64'h4);
endfunction
localparam longint unsigned SLINK_RAW_MODE_OUT_CH_MASK_NUM = 64'h1;
function automatic longint unsigned SLINK_TX_PHY_CLK_DIV_BASE_ADDR(input int unsigned tx_phy_clk_div_idx);
    return 64'h3006300 + (tx_phy_clk_div_idx * 64'h4);
endfunction
localparam longint unsigned SLINK_TX_PHY_CLK_DIV_NUM = 64'h1;
function automatic longint unsigned SLINK_TX_PHY_CLK_START_BASE_ADDR(input int unsigned tx_phy_clk_start_idx);
    return 64'h3006400 + (tx_phy_clk_start_idx * 64'h4);
endfunction
localparam longint unsigned SLINK_TX_PHY_CLK_START_NUM = 64'h1;
function automatic longint unsigned SLINK_TX_PHY_CLK_END_BASE_ADDR(input int unsigned tx_phy_clk_end_idx);
    return 64'h3006500 + (tx_phy_clk_end_idx * 64'h4);
endfunction
localparam longint unsigned SLINK_TX_PHY_CLK_END_NUM = 64'h1;
localparam longint unsigned SLINK_CHANNEL_ALLOC_TX_CFG_BASE_ADDR = 64'h3006600;
localparam longint unsigned SLINK_CHANNEL_ALLOC_TX_CTRL_BASE_ADDR = 64'h3006604;
localparam longint unsigned SLINK_CHANNEL_ALLOC_RX_CFG_BASE_ADDR = 64'h3006608;
localparam longint unsigned SLINK_CHANNEL_ALLOC_RX_CTRL_BASE_ADDR = 64'h300660C;
function automatic longint unsigned SLINK_CHANNEL_ALLOC_TX_CH_EN_BASE_ADDR(input int unsigned channel_alloc_tx_ch_en_idx);
    return 64'h3006700 + (channel_alloc_tx_ch_en_idx * 64'h4);
endfunction
localparam longint unsigned SLINK_CHANNEL_ALLOC_TX_CH_EN_NUM = 64'h1;
function automatic longint unsigned SLINK_CHANNEL_ALLOC_RX_CH_EN_BASE_ADDR(input int unsigned channel_alloc_rx_ch_en_idx);
    return 64'h3006800 + (channel_alloc_rx_ch_en_idx * 64'h4);
endfunction
localparam longint unsigned SLINK_CHANNEL_ALLOC_RX_CH_EN_NUM = 64'h1;
localparam longint unsigned VGA_STATUS_BASE_ADDR = 64'h3007000;
localparam longint unsigned VGA__END_BASE_ADDR = 64'h3007FFC;
localparam longint unsigned USB_STATUS_BASE_ADDR = 64'h3008000;
localparam longint unsigned USB__END_BASE_ADDR = 64'h3008FFC;
localparam longint unsigned BUS_ERR_STATUS_BASE_ADDR = 64'h3009000;
localparam longint unsigned BUS_ERR__END_BASE_ADDR = 64'h300903C;
localparam longint unsigned TAGGER_STATUS_BASE_ADDR = 64'h300A000;
localparam longint unsigned TAGGER__END_BASE_ADDR = 64'h300A0FC;
localparam longint unsigned PLIC_STATUS_BASE_ADDR = 64'h4000000;
localparam longint unsigned PLIC__END_BASE_ADDR = 64'h7FFFFFC;
localparam longint unsigned CLIC_STATUS_BASE_ADDR = 64'h8000000;
localparam longint unsigned CLIC__END_BASE_ADDR = 64'h803FFFC;


typedef enum logic [1:0] {
    PASSIVE = 2'd0,
    SPI_SDCARD = 2'd1,
    SPI_S25FS512S = 2'd2,
    I2C_24XX1025 = 2'd3
} BootMode_e;

endpackage;
