#!/usr/bin/env python3
#
# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Nicole Narr <narrn@student.ethz.ch>
# Christopher Reinwardt <creinwar@student.ethz.ch>
#
# Fabian Schuiki <fschuiki@iis.ee.ethz.ch>
# Florian Zaruba <zarubaf@iis.ee.ethz.ch>
# Stefan Mach <smach@iis.ee.ethz.ch>
# Thomas Benz <tbenz@iis.ee.ethz.ch>
# Paul Scheffler <paulsc@iis.ee.ethz.ch>
# Wolfgang Roenninger <wroennin@iis.ee.ethz.ch>
# Gianna Paulin <pauling@iis.ee.ethz.ch>
# Tim Fischer <fischeti@iis.ee.ethz.ch>
# Enrico Zelioli <ezelioli@iis.ee.ethz.ch>

import os
import argparse

# Parse arguments.
parser = argparse.ArgumentParser(description="Generate rv_plic.cfg.hjson")
parser.add_argument(
    "--num-cores",
    "-n",
    dest="num_cores",
    default=1,
    type=int,
    help=
    "Number of cores attached to the PLIC. The number of PLIC targets is set accordingly (2 * num-cores)"
)
args = parser.parse_args()

num_targets = args.num_cores * 2

# Emit the code.
print("""
// Copyright 2022 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Paul Scheffler <paulsc@iis.ee.ethz.ch>
// Enrico Zelioli <ezelioli@iis.ee.ethz.ch>
// AUTOMATICALLY GENERATED by {script}; edit the script instead.

{{
    instance_name: \"rv_plic\",
    param_values: {{
        src: 58,
        target: {targets},  // We need *two targets* per hart: M and S modes
        prio: 7,
        nonstd_regs: 0  // Do *not* include these: MSIPs are not used and we use a 64 MiB address space
    }},
}}

""".strip().format(
    script=os.path.basename(__file__),
    targets=num_targets
))
