#!/usr/bin/env python3
#
# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Nicole Narr <narrn@student.ethz.ch>
# Christopher Reinwardt <creinwar@student.ethz.ch>
#
# Fabian Schuiki <fschuiki@iis.ee.ethz.ch>
# Florian Zaruba <zarubaf@iis.ee.ethz.ch>
# Stefan Mach <smach@iis.ee.ethz.ch>
# Thomas Benz <tbenz@iis.ee.ethz.ch>
# Paul Scheffler <paulsc@iis.ee.ethz.ch>
# Wolfgang Roenninger <wroennin@iis.ee.ethz.ch>
# Gianna Paulin <pauling@iis.ee.ethz.ch>
# Tim Fischer <fischeti@iis.ee.ethz.ch>
# Enrico Zelioli <ezelioli@iis.ee.ethz.ch>

import os
import argparse

# Parse arguments.
parser = argparse.ArgumentParser(description="Generate rv_plic.cfg.hjson")
parser.add_argument(
    "num_cores",
    type=int,
    help="Number of attached cores."
)
parser.add_argument(
    "num_srcs",
    type=int,
    help="Bit width of interrupt priority."
)
parser.add_argument(
    "prio_width",
    type=int,
    help="Bit width of interrupt priority."
)
args = parser.parse_args()

# We need *two targets* per hart: M and S modes
num_targets = 2 * args.num_cores

# Emit the code.
print("""
// Copyright 2022 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Paul Scheffler <paulsc@iis.ee.ethz.ch>
// Enrico Zelioli <ezelioli@iis.ee.ethz.ch>
// AUTOMATICALLY GENERATED by {script}; edit the script instead.

{{
    instance_name: \"rv_plic\",
    param_values: {{
        src: {num_srcs},
        target: {num_targets},
        prio: {prio_width},
        nonstd_regs: 0
    }},
}}
    """.strip().format(
        script=os.path.basename(__file__),
        num_srcs=args.num_srcs,
        num_targets=num_targets,
        prio_width=args.prio_width
))
