<%!
    # Copyright 2026 ETH Zurich and University of Bologna.
    # Licensed under the Apache License, Version 2.0, see LICENSE for details.
    # SPDX-License-Identifier: Apache-2.0
    #
    # Local override of PeakRDL-rawheader's stock ldh.mako. The stock template
    # unrolls every *register* array into one PROVIDE() per element (e.g. one
    # per CLIC interrupt line: 256+ symbols just for clicint), even though
    # nothing in this repository's linker scripts or startup code ever
    # addresses an individual array element by name -- they all compute
    # element addresses from a base and a stride, the way software indexes
    # into the array struct the C header already exports. This template keeps
    # that same per-array-not-per-element granularity for registers: a single
    # base_addr, plus num/stride for arrays. block-level arrays (regfile/
    # addrmap instances, e.g. one CLIC window per VS context) are left as the
    # stock template unrolls them, since those counts stay small and a
    # specific instance's address is genuinely useful on its own.
    #
    # If register-level unrolling is ever needed for some symbol, do it there
    # explicitly rather than reverting this file to the stock behaviour for
    # everything.

    from peakrdl_rawheader.utils import fmt_hex, fmt_license

    def iter_instances(base_addr, array_info):
        """Yield (index_str, address) for each instance; single entry for non-arrays."""
        if not array_info:
            yield (None, base_addr)
            return
        a = array_info[-1]
        for i in range(a['dim'][-1]):
            yield (str(i), base_addr + i * a['stride'])

    def ld_sym(name_parts, idx, suffix):
        parts = name_parts + ([idx] if idx is not None else []) + [suffix]
        return "__" + "_".join(parts).lower() + "__"

    def ld_region(name_parts, idx):
        parts = name_parts + ([idx] if idx is not None else [])
        return "_".join(parts).lower()
%>\
% if license_str is not None:
${fmt_license(license_str, "ldh")}
% endif
/* Generated by PeakRDL raw-header, with a locally trimmed register template:
   see sw/link/rawheader_ldh.mako */

% if emit_ldh_memory and memories:
/* Memories */
MEMORY
{
% for mem in memories:
% for idx, addr in iter_instances(mem["addr"], mem["array_info"]):
  ${ld_region(mem["name"], idx)}${" (" + mem["ld_attrs"] + ")" if mem["ld_attrs"] else ""} : ORIGIN = ${fmt_hex(addr, "ldh")}, LENGTH = ${fmt_hex(mem["size"], "ldh")}
% endfor
% endfor
}

% endif
% if emit_ldh_symbols:
/* Blocks */
% for block in blocks:
% for idx, addr in iter_instances(block["addr"], block["array_info"]):
PROVIDE(${ld_sym(block["name"], idx, "base_addr")} = ${fmt_hex(addr, "ldh")});
% endfor
PROVIDE(${ld_sym(block["name"], None, "size")} = ${fmt_hex(block["size"], "ldh")});
% if "stride" in block:
PROVIDE(${ld_sym(block["name"], None, "num")} = ${fmt_hex(block["array_info"][-1]["dim"][-1], "ldh")});
PROVIDE(${ld_sym(block["name"], None, "stride")} = ${fmt_hex(block["stride"], "ldh")});
% if "total_size" in block:
PROVIDE(${ld_sym(block["name"], None, "total_size")} = ${fmt_hex(block["total_size"], "ldh")});
% endif
% endif

% endfor
/* Registers. Unlike the stock template, array registers get one base_addr
   (their first element) plus num/stride, not one base_addr per element. */
% for reg in registers:
PROVIDE(${ld_sym(reg["name"], None, "base_addr")} = ${fmt_hex(reg["addr"], "ldh")});
% if reg["array_info"]:
PROVIDE(${ld_sym(reg["name"], None, "num")} = ${fmt_hex(reg["array_info"][-1]["dim"][-1], "ldh")});
PROVIDE(${ld_sym(reg["name"], None, "stride")} = ${fmt_hex(reg["array_info"][-1]["stride"], "ldh")});
% endif

% endfor
% endif
