// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package cheshire_register_file_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [1:0]  d;
  } cheshire_register_file_hw2reg_boot_mode_reg_t;

  typedef struct packed {
    logic        d;
  } cheshire_register_file_hw2reg_fll_lock_reg_t;

  // HW -> register type
  typedef struct packed {
    cheshire_register_file_hw2reg_boot_mode_reg_t boot_mode; // [2:1]
    cheshire_register_file_hw2reg_fll_lock_reg_t fll_lock; // [0:0]
  } cheshire_register_file_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CHESHIRE_REGISTER_FILE_VERSION_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] CHESHIRE_REGISTER_FILE_SCRATCH_0_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] CHESHIRE_REGISTER_FILE_SCRATCH_1_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] CHESHIRE_REGISTER_FILE_SCRATCH_2_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] CHESHIRE_REGISTER_FILE_SCRATCH_3_OFFSET = 5'h 10;
  parameter logic [BlockAw-1:0] CHESHIRE_REGISTER_FILE_BOOT_MODE_OFFSET = 5'h 14;
  parameter logic [BlockAw-1:0] CHESHIRE_REGISTER_FILE_FLL_LOCK_OFFSET = 5'h 18;

  // Reset values for hwext registers and their fields
  parameter logic [1:0] CHESHIRE_REGISTER_FILE_BOOT_MODE_RESVAL = 2'h 0;
  parameter logic [0:0] CHESHIRE_REGISTER_FILE_FLL_LOCK_RESVAL = 1'h 0;

  // Register index
  typedef enum int {
    CHESHIRE_REGISTER_FILE_VERSION,
    CHESHIRE_REGISTER_FILE_SCRATCH_0,
    CHESHIRE_REGISTER_FILE_SCRATCH_1,
    CHESHIRE_REGISTER_FILE_SCRATCH_2,
    CHESHIRE_REGISTER_FILE_SCRATCH_3,
    CHESHIRE_REGISTER_FILE_BOOT_MODE,
    CHESHIRE_REGISTER_FILE_FLL_LOCK
  } cheshire_register_file_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CHESHIRE_REGISTER_FILE_PERMIT [7] = '{
    4'b 0011, // index[0] CHESHIRE_REGISTER_FILE_VERSION
    4'b 1111, // index[1] CHESHIRE_REGISTER_FILE_SCRATCH_0
    4'b 1111, // index[2] CHESHIRE_REGISTER_FILE_SCRATCH_1
    4'b 1111, // index[3] CHESHIRE_REGISTER_FILE_SCRATCH_2
    4'b 1111, // index[4] CHESHIRE_REGISTER_FILE_SCRATCH_3
    4'b 0001, // index[5] CHESHIRE_REGISTER_FILE_BOOT_MODE
    4'b 0001  // index[6] CHESHIRE_REGISTER_FILE_FLL_LOCK
  };

endpackage

