// Copyright 2025 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef CHESHIRE_H
#define CHESHIRE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Mem - cheshire::extrom
typedef struct __attribute__ ((__packed__)) {
    uint32_t mem[12288];
} cheshire__extrom_t;

// Reg - periph_stub_t::status
#define PERIPH_STUB_T__STATUS__STATUS_bm 0xffffffff
#define PERIPH_STUB_T__STATUS__STATUS_bp 0
#define PERIPH_STUB_T__STATUS__STATUS_bw 32
#define PERIPH_STUB_T__STATUS__STATUS_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t status :32;
    } f;
    uint32_t w;
} periph_stub_t__status_t;

// Addrmap - periph_stub_t
typedef struct __attribute__ ((__packed__)) {
    periph_stub_t__status_t status;
} periph_stub_t_t;

// Mem - cheshire::bootrom
typedef struct __attribute__ ((__packed__)) {
    uint32_t mem[4096];
} cheshire__bootrom_t;

// Reg - cheshire_regs::scratch
#define CHESHIRE_REGS__SCRATCH__SCRATCH_bm 0xffffffff
#define CHESHIRE_REGS__SCRATCH__SCRATCH_bp 0
#define CHESHIRE_REGS__SCRATCH__SCRATCH_bw 32
#define CHESHIRE_REGS__SCRATCH__SCRATCH_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t scratch :32;
    } f;
    uint32_t w;
} cheshire_regs__scratch_t;

// Reg - cheshire_regs::boot_mode
#define CHESHIRE_REGS__BOOT_MODE__BOOT_MODE_bm 0x3
#define CHESHIRE_REGS__BOOT_MODE__BOOT_MODE_bp 0
#define CHESHIRE_REGS__BOOT_MODE__BOOT_MODE_bw 2
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t boot_mode :2;
        uint32_t :30;
    } f;
    uint32_t w;
} cheshire_regs__boot_mode_t;

// Reg - cheshire_regs::rtc_freq
#define CHESHIRE_REGS__RTC_FREQ__REF_FREQ_bm 0xffffffff
#define CHESHIRE_REGS__RTC_FREQ__REF_FREQ_bp 0
#define CHESHIRE_REGS__RTC_FREQ__REF_FREQ_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t ref_freq :32;
    } f;
    uint32_t w;
} cheshire_regs__rtc_freq_t;

// Reg - cheshire_regs::platform_rom
#define CHESHIRE_REGS__PLATFORM_ROM__PLATFORM_ROM_bm 0xffffffff
#define CHESHIRE_REGS__PLATFORM_ROM__PLATFORM_ROM_bp 0
#define CHESHIRE_REGS__PLATFORM_ROM__PLATFORM_ROM_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t platform_rom :32;
    } f;
    uint32_t w;
} cheshire_regs__platform_rom_t;

// Reg - cheshire_regs::num_int_harts
#define CHESHIRE_REGS__NUM_INT_HARTS__NUM_HARTS_bm 0xffffffff
#define CHESHIRE_REGS__NUM_INT_HARTS__NUM_HARTS_bp 0
#define CHESHIRE_REGS__NUM_INT_HARTS__NUM_HARTS_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t num_harts :32;
    } f;
    uint32_t w;
} cheshire_regs__num_int_harts_t;

// Reg - cheshire_regs::hw_features
#define CHESHIRE_REGS__HW_FEATURES__BOOTROM_bm 0x1
#define CHESHIRE_REGS__HW_FEATURES__BOOTROM_bp 0
#define CHESHIRE_REGS__HW_FEATURES__BOOTROM_bw 1
#define CHESHIRE_REGS__HW_FEATURES__LLC_bm 0x2
#define CHESHIRE_REGS__HW_FEATURES__LLC_bp 1
#define CHESHIRE_REGS__HW_FEATURES__LLC_bw 1
#define CHESHIRE_REGS__HW_FEATURES__UART_bm 0x4
#define CHESHIRE_REGS__HW_FEATURES__UART_bp 2
#define CHESHIRE_REGS__HW_FEATURES__UART_bw 1
#define CHESHIRE_REGS__HW_FEATURES__SPI_HOST_bm 0x8
#define CHESHIRE_REGS__HW_FEATURES__SPI_HOST_bp 3
#define CHESHIRE_REGS__HW_FEATURES__SPI_HOST_bw 1
#define CHESHIRE_REGS__HW_FEATURES__I2C_bm 0x10
#define CHESHIRE_REGS__HW_FEATURES__I2C_bp 4
#define CHESHIRE_REGS__HW_FEATURES__I2C_bw 1
#define CHESHIRE_REGS__HW_FEATURES__GPIO_bm 0x20
#define CHESHIRE_REGS__HW_FEATURES__GPIO_bp 5
#define CHESHIRE_REGS__HW_FEATURES__GPIO_bw 1
#define CHESHIRE_REGS__HW_FEATURES__DMA_bm 0x40
#define CHESHIRE_REGS__HW_FEATURES__DMA_bp 6
#define CHESHIRE_REGS__HW_FEATURES__DMA_bw 1
#define CHESHIRE_REGS__HW_FEATURES__SERIAL_LINK_bm 0x80
#define CHESHIRE_REGS__HW_FEATURES__SERIAL_LINK_bp 7
#define CHESHIRE_REGS__HW_FEATURES__SERIAL_LINK_bw 1
#define CHESHIRE_REGS__HW_FEATURES__VGA_bm 0x100
#define CHESHIRE_REGS__HW_FEATURES__VGA_bp 8
#define CHESHIRE_REGS__HW_FEATURES__VGA_bw 1
#define CHESHIRE_REGS__HW_FEATURES__USB_bm 0x200
#define CHESHIRE_REGS__HW_FEATURES__USB_bp 9
#define CHESHIRE_REGS__HW_FEATURES__USB_bw 1
#define CHESHIRE_REGS__HW_FEATURES__AXIRT_bm 0x400
#define CHESHIRE_REGS__HW_FEATURES__AXIRT_bp 10
#define CHESHIRE_REGS__HW_FEATURES__AXIRT_bw 1
#define CHESHIRE_REGS__HW_FEATURES__CLIC_bm 0x800
#define CHESHIRE_REGS__HW_FEATURES__CLIC_bp 11
#define CHESHIRE_REGS__HW_FEATURES__CLIC_bw 1
#define CHESHIRE_REGS__HW_FEATURES__IRQ_ROUTER_bm 0x1000
#define CHESHIRE_REGS__HW_FEATURES__IRQ_ROUTER_bp 12
#define CHESHIRE_REGS__HW_FEATURES__IRQ_ROUTER_bw 1
#define CHESHIRE_REGS__HW_FEATURES__BUS_ERR_bm 0x2000
#define CHESHIRE_REGS__HW_FEATURES__BUS_ERR_bp 13
#define CHESHIRE_REGS__HW_FEATURES__BUS_ERR_bw 1
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t bootrom :1;
        uint32_t llc :1;
        uint32_t uart :1;
        uint32_t spi_host :1;
        uint32_t i2c :1;
        uint32_t gpio :1;
        uint32_t dma :1;
        uint32_t serial_link :1;
        uint32_t vga :1;
        uint32_t usb :1;
        uint32_t axirt :1;
        uint32_t clic :1;
        uint32_t irq_router :1;
        uint32_t bus_err :1;
        uint32_t :18;
    } f;
    uint32_t w;
} cheshire_regs__hw_features_t;

// Reg - cheshire_regs::llc_size
#define CHESHIRE_REGS__LLC_SIZE__LLC_SIZE_bm 0xffffffff
#define CHESHIRE_REGS__LLC_SIZE__LLC_SIZE_bp 0
#define CHESHIRE_REGS__LLC_SIZE__LLC_SIZE_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t llc_size :32;
    } f;
    uint32_t w;
} cheshire_regs__llc_size_t;

// Reg - cheshire_regs::vga_params
#define CHESHIRE_REGS__VGA_PARAMS__RED_WIDTH_bm 0xff
#define CHESHIRE_REGS__VGA_PARAMS__RED_WIDTH_bp 0
#define CHESHIRE_REGS__VGA_PARAMS__RED_WIDTH_bw 8
#define CHESHIRE_REGS__VGA_PARAMS__GREEN_WIDTH_bm 0xff00
#define CHESHIRE_REGS__VGA_PARAMS__GREEN_WIDTH_bp 8
#define CHESHIRE_REGS__VGA_PARAMS__GREEN_WIDTH_bw 8
#define CHESHIRE_REGS__VGA_PARAMS__BLUE_WIDTH_bm 0xff0000
#define CHESHIRE_REGS__VGA_PARAMS__BLUE_WIDTH_bp 16
#define CHESHIRE_REGS__VGA_PARAMS__BLUE_WIDTH_bw 8
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t red_width :8;
        uint32_t green_width :8;
        uint32_t blue_width :8;
        uint32_t :8;
    } f;
    uint32_t w;
} cheshire_regs__vga_params_t;

// Addrmap - cheshire_regs
typedef struct __attribute__ ((__packed__)) {
    cheshire_regs__scratch_t scratch[16];
    cheshire_regs__boot_mode_t boot_mode;
    cheshire_regs__rtc_freq_t rtc_freq;
    cheshire_regs__platform_rom_t platform_rom;
    cheshire_regs__num_int_harts_t num_int_harts;
    cheshire_regs__hw_features_t hw_features;
    cheshire_regs__llc_size_t llc_size;
    cheshire_regs__vga_params_t vga_params;
} cheshire_regs_t;

// Mem - cheshire::spm
typedef struct __attribute__ ((__packed__)) {
    uint32_t mem[16384];
} cheshire__spm_t;

// Mem - cheshire::dram
typedef struct __attribute__ ((__packed__)) {
    uint32_t mem[2097152];
} cheshire__dram_t;

// Addrmap - cheshire
typedef struct __attribute__ ((__packed__)) {
    cheshire__extrom_t extrom;
    uint8_t RESERVED_c000_ffffff[0xff4000];
    periph_stub_t_t dma;
    uint8_t RESERVED_1000004_1ffffff[0xfffffc];
    cheshire__bootrom_t bootrom;
    uint8_t RESERVED_2004000_203ffff[0x3c000];
    periph_stub_t_t clint;
    uint8_t RESERVED_2040004_20bffff[0x7fffc];
    periph_stub_t_t axirt;
    uint8_t RESERVED_20c0004_2ffffff[0xf3fffc];
    cheshire_regs_t regs;
    uint8_t RESERVED_300005c_3000fff[0xfa4];
    periph_stub_t_t llc;
    uint8_t RESERVED_3001004_3001fff[0xffc];
    periph_stub_t_t uart;
    uint8_t RESERVED_3002004_3002fff[0xffc];
    periph_stub_t_t i2c;
    uint8_t RESERVED_3003004_3003fff[0xffc];
    periph_stub_t_t spih;
    uint8_t RESERVED_3004004_3004fff[0xffc];
    periph_stub_t_t gpio;
    uint8_t RESERVED_3005004_3005fff[0xffc];
    periph_stub_t_t slink;
    uint8_t RESERVED_3006004_3006fff[0xffc];
    periph_stub_t_t vga;
    uint8_t RESERVED_3007004_3007fff[0xffc];
    periph_stub_t_t usb;
    uint8_t RESERVED_3008004_3008fff[0xffc];
    periph_stub_t_t bus_err;
    uint8_t RESERVED_3009004_3ffffff[0xff6ffc];
    periph_stub_t_t plic;
    uint8_t RESERVED_4000004_7ffffff[0x3fffffc];
    periph_stub_t_t clic;
    uint8_t RESERVED_8000004_fffffff[0x7fffffc];
    cheshire__spm_t spm;
    uint8_t RESERVED_10010000_7fffffff[0x6fff0000];
    cheshire__dram_t dram;
} cheshire_t;


static_assert(sizeof(cheshire_t) == 0x80800000, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* CHESHIRE_H */
