// Copyright 2025 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef CLINT_H
#define CLINT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - clint::msip
#define CLINT__MSIP__PENDING_bm 0x1
#define CLINT__MSIP__PENDING_bp 0
#define CLINT__MSIP__PENDING_bw 1
#define CLINT__MSIP__PENDING_reset 0x0
#define CLINT__MSIP__RSVD_bm 0xfffffffe
#define CLINT__MSIP__RSVD_bp 1
#define CLINT__MSIP__RSVD_bw 31
#define CLINT__MSIP__RSVD_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t pending :1;
        uint32_t rsvd :31;
    } f;
    uint32_t w;
} clint__msip_t;

// Reg - clint::mtimecmp
#define CLINT__MTIMECMP__LOW_bm 0xffffffff
#define CLINT__MTIMECMP__LOW_bp 0
#define CLINT__MTIMECMP__LOW_bw 32
#define CLINT__MTIMECMP__LOW_reset 0x0
#define CLINT__MTIMECMP__HIGH_bm 0xffffffff00000000
#define CLINT__MTIMECMP__HIGH_bp 32
#define CLINT__MTIMECMP__HIGH_bw 32
#define CLINT__MTIMECMP__HIGH_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint64_t low :32;
        uint64_t high :32;
    } f;
    uint64_t w;
} clint__mtimecmp_t;

// Reg - clint::mtime
#define CLINT__MTIME__LOW_bm 0xffffffff
#define CLINT__MTIME__LOW_bp 0
#define CLINT__MTIME__LOW_bw 32
#define CLINT__MTIME__LOW_reset 0x0
#define CLINT__MTIME__HIGH_bm 0xffffffff00000000
#define CLINT__MTIME__HIGH_bp 32
#define CLINT__MTIME__HIGH_bw 32
#define CLINT__MTIME__HIGH_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint64_t low :32;
        uint64_t high :32;
    } f;
    uint64_t w;
} clint__mtime_t;

// Addrmap - clint
typedef struct __attribute__ ((__packed__)) {
    clint__msip_t msip[2];
    uint8_t RESERVED_8_3fff[0x3ff8];
    clint__mtimecmp_t mtimecmp[2];
    uint8_t RESERVED_4010_bff7[0x7fe8];
    clint__mtime_t mtime;
} clint_t;


static_assert(sizeof(clint_t) == 0xc000, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* CLINT_H */
