// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef IDMA_H
#define IDMA_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - idma_reg64_2d.conf
#define IDMA_REG64_2D__CONF__DECOUPLE_AW_bm 0x1
#define IDMA_REG64_2D__CONF__DECOUPLE_AW_bp 0
#define IDMA_REG64_2D__CONF__DECOUPLE_AW_bw 1
#define IDMA_REG64_2D__CONF__DECOUPLE_AW_reset 0x0
#define IDMA_REG64_2D__CONF__DECOUPLE_RW_bm 0x2
#define IDMA_REG64_2D__CONF__DECOUPLE_RW_bp 1
#define IDMA_REG64_2D__CONF__DECOUPLE_RW_bw 1
#define IDMA_REG64_2D__CONF__DECOUPLE_RW_reset 0x0
#define IDMA_REG64_2D__CONF__SRC_REDUCE_LEN_bm 0x4
#define IDMA_REG64_2D__CONF__SRC_REDUCE_LEN_bp 2
#define IDMA_REG64_2D__CONF__SRC_REDUCE_LEN_bw 1
#define IDMA_REG64_2D__CONF__SRC_REDUCE_LEN_reset 0x0
#define IDMA_REG64_2D__CONF__DST_REDUCE_LEN_bm 0x8
#define IDMA_REG64_2D__CONF__DST_REDUCE_LEN_bp 3
#define IDMA_REG64_2D__CONF__DST_REDUCE_LEN_bw 1
#define IDMA_REG64_2D__CONF__DST_REDUCE_LEN_reset 0x0
#define IDMA_REG64_2D__CONF__SRC_MAX_LLEN_bm 0x70
#define IDMA_REG64_2D__CONF__SRC_MAX_LLEN_bp 4
#define IDMA_REG64_2D__CONF__SRC_MAX_LLEN_bw 3
#define IDMA_REG64_2D__CONF__SRC_MAX_LLEN_reset 0x0
#define IDMA_REG64_2D__CONF__DST_MAX_LLEN_bm 0x380
#define IDMA_REG64_2D__CONF__DST_MAX_LLEN_bp 7
#define IDMA_REG64_2D__CONF__DST_MAX_LLEN_bw 3
#define IDMA_REG64_2D__CONF__DST_MAX_LLEN_reset 0x0
#define IDMA_REG64_2D__CONF__ENABLE_ND_bm 0xc00
#define IDMA_REG64_2D__CONF__ENABLE_ND_bp 10
#define IDMA_REG64_2D__CONF__ENABLE_ND_bw 2
#define IDMA_REG64_2D__CONF__ENABLE_ND_reset 0x0
#define IDMA_REG64_2D__CONF__SRC_PROTOCOL_bm 0x7000
#define IDMA_REG64_2D__CONF__SRC_PROTOCOL_bp 12
#define IDMA_REG64_2D__CONF__SRC_PROTOCOL_bw 3
#define IDMA_REG64_2D__CONF__SRC_PROTOCOL_reset 0x0
#define IDMA_REG64_2D__CONF__DST_PROTOCOL_bm 0x38000
#define IDMA_REG64_2D__CONF__DST_PROTOCOL_bp 15
#define IDMA_REG64_2D__CONF__DST_PROTOCOL_bw 3
#define IDMA_REG64_2D__CONF__DST_PROTOCOL_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t decouple_aw :1;
        uint32_t decouple_rw :1;
        uint32_t src_reduce_len :1;
        uint32_t dst_reduce_len :1;
        uint32_t src_max_llen :3;
        uint32_t dst_max_llen :3;
        uint32_t enable_nd :2;
        uint32_t src_protocol :3;
        uint32_t dst_protocol :3;
        uint32_t :14;
    } f;
    uint32_t w;
} idma_reg64_2d__conf_t;

// reg - idma_reg64_2d.status[]
#define IDMA_REG64_2D__STATUSX__BUSY_bm 0x3ff
#define IDMA_REG64_2D__STATUSX__BUSY_bp 0
#define IDMA_REG64_2D__STATUSX__BUSY_bw 10
#define IDMA_REG64_2D__STATUSX__BUSY_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t busy :10;
        uint32_t :22;
    } f;
    uint32_t w;
} idma_reg64_2d__statusx_t;

// reg - idma_reg64_2d.next_id[]
#define IDMA_REG64_2D__NEXT_IDX__NEXT_ID_bm 0xffffffff
#define IDMA_REG64_2D__NEXT_IDX__NEXT_ID_bp 0
#define IDMA_REG64_2D__NEXT_IDX__NEXT_ID_bw 32
#define IDMA_REG64_2D__NEXT_IDX__NEXT_ID_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t next_id :32;
    } f;
    uint32_t w;
} idma_reg64_2d__next_idx_t;

// reg - idma_reg64_2d.done_id[]
#define IDMA_REG64_2D__DONE_IDX__DONE_ID_bm 0xffffffff
#define IDMA_REG64_2D__DONE_IDX__DONE_ID_bp 0
#define IDMA_REG64_2D__DONE_IDX__DONE_ID_bw 32
#define IDMA_REG64_2D__DONE_IDX__DONE_ID_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t done_id :32;
    } f;
    uint32_t w;
} idma_reg64_2d__done_idx_t;

// reg - idma_reg64_2d.dst_addr[]
#define IDMA_REG64_2D__DST_ADDRX__DST_ADDR_bm 0xffffffff
#define IDMA_REG64_2D__DST_ADDRX__DST_ADDR_bp 0
#define IDMA_REG64_2D__DST_ADDRX__DST_ADDR_bw 32
#define IDMA_REG64_2D__DST_ADDRX__DST_ADDR_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t dst_addr :32;
    } f;
    uint32_t w;
} idma_reg64_2d__dst_addrx_t;

// reg - idma_reg64_2d.src_addr[]
#define IDMA_REG64_2D__SRC_ADDRX__SRC_ADDR_bm 0xffffffff
#define IDMA_REG64_2D__SRC_ADDRX__SRC_ADDR_bp 0
#define IDMA_REG64_2D__SRC_ADDRX__SRC_ADDR_bw 32
#define IDMA_REG64_2D__SRC_ADDRX__SRC_ADDR_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t src_addr :32;
    } f;
    uint32_t w;
} idma_reg64_2d__src_addrx_t;

// reg - idma_reg64_2d.length[]
#define IDMA_REG64_2D__LENGTHX__LENGTH_bm 0xffffffff
#define IDMA_REG64_2D__LENGTHX__LENGTH_bp 0
#define IDMA_REG64_2D__LENGTHX__LENGTH_bw 32
#define IDMA_REG64_2D__LENGTHX__LENGTH_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t length :32;
    } f;
    uint32_t w;
} idma_reg64_2d__lengthx_t;

// reg - idma_reg64_2d.dim[].dst_stride[]
#define IDMA_REG64_2D__DIMX__DST_STRIDEX__DST_STRIDE_bm 0xffffffff
#define IDMA_REG64_2D__DIMX__DST_STRIDEX__DST_STRIDE_bp 0
#define IDMA_REG64_2D__DIMX__DST_STRIDEX__DST_STRIDE_bw 32
#define IDMA_REG64_2D__DIMX__DST_STRIDEX__DST_STRIDE_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t dst_stride :32;
    } f;
    uint32_t w;
} idma_reg64_2d__dimx__dst_stridex_t;

// reg - idma_reg64_2d.dim[].src_stride[]
#define IDMA_REG64_2D__DIMX__SRC_STRIDEX__SRC_STRIDE_bm 0xffffffff
#define IDMA_REG64_2D__DIMX__SRC_STRIDEX__SRC_STRIDE_bp 0
#define IDMA_REG64_2D__DIMX__SRC_STRIDEX__SRC_STRIDE_bw 32
#define IDMA_REG64_2D__DIMX__SRC_STRIDEX__SRC_STRIDE_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t src_stride :32;
    } f;
    uint32_t w;
} idma_reg64_2d__dimx__src_stridex_t;

// reg - idma_reg64_2d.dim[].reps[]
#define IDMA_REG64_2D__DIMX__REPSX__REPS_bm 0xffffffff
#define IDMA_REG64_2D__DIMX__REPSX__REPS_bp 0
#define IDMA_REG64_2D__DIMX__REPSX__REPS_bw 32
#define IDMA_REG64_2D__DIMX__REPSX__REPS_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t reps :32;
    } f;
    uint32_t w;
} idma_reg64_2d__dimx__repsx_t;

// regfile - idma_reg64_2d.dim[]
typedef struct __attribute__ ((__packed__)) {
    idma_reg64_2d__dimx__dst_stridex_t dst_stride[2];
    idma_reg64_2d__dimx__src_stridex_t src_stride[2];
    idma_reg64_2d__dimx__repsx_t reps[2];
} idma_reg64_2d__dimx_t;

// reg - idma_reg64_2d.compute_cfg
#define IDMA_REG64_2D__COMPUTE_CFG__COMPUTE_ENABLE_bm 0x1
#define IDMA_REG64_2D__COMPUTE_CFG__COMPUTE_ENABLE_bp 0
#define IDMA_REG64_2D__COMPUTE_CFG__COMPUTE_ENABLE_bw 1
#define IDMA_REG64_2D__COMPUTE_CFG__COMPUTE_ENABLE_reset 0x0
#define IDMA_REG64_2D__COMPUTE_CFG__COMPUTE_OP_bm 0x1e
#define IDMA_REG64_2D__COMPUTE_CFG__COMPUTE_OP_bp 1
#define IDMA_REG64_2D__COMPUTE_CFG__COMPUTE_OP_bw 4
#define IDMA_REG64_2D__COMPUTE_CFG__COMPUTE_OP_reset 0x0
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_MODE_bm 0x60
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_MODE_bp 5
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_MODE_bw 2
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_MODE_reset 0x0
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_TENSOR_M_bm 0x7ff80
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_TENSOR_M_bp 7
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_TENSOR_M_bw 12
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_TENSOR_M_reset 0x0
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_TENSOR_N_bm 0x7ff80000
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_TENSOR_N_bp 19
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_TENSOR_N_bw 12
#define IDMA_REG64_2D__COMPUTE_CFG__TRANSPOSE_TENSOR_N_reset 0x0
#define IDMA_REG64_2D__COMPUTE_CFG__RESERVED_bm 0x80000000
#define IDMA_REG64_2D__COMPUTE_CFG__RESERVED_bp 31
#define IDMA_REG64_2D__COMPUTE_CFG__RESERVED_bw 1
#define IDMA_REG64_2D__COMPUTE_CFG__RESERVED_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t compute_enable :1;
        uint32_t compute_op :4;
        uint32_t transpose_mode :2;
        uint32_t transpose_tensor_m :12;
        uint32_t transpose_tensor_n :12;
        uint32_t reserved :1;
    } f;
    uint32_t w;
} idma_reg64_2d__compute_cfg_t;

// addrmap - idma_reg64_2d
typedef struct __attribute__ ((__packed__)) {
    idma_reg64_2d__conf_t conf;
    idma_reg64_2d__statusx_t status[16];
    idma_reg64_2d__next_idx_t next_id[16];
    idma_reg64_2d__done_idx_t done_id[16];
    uint8_t RESERVED_c4_cf[0xc];
    idma_reg64_2d__dst_addrx_t dst_addr[2];
    idma_reg64_2d__src_addrx_t src_addr[2];
    idma_reg64_2d__lengthx_t length[2];
    uint8_t RESERVED_e8_ff[0x18];
    idma_reg64_2d__dimx_t dim[1];
    idma_reg64_2d__compute_cfg_t compute_cfg;
} idma_reg64_2d_t;


static_assert(sizeof(idma_reg64_2d_t) == 0x11c, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* IDMA_H */
