# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Paul Scheffler <paulsc@iis.ee.ethz.ch>

name: publish-docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
      -
        name: Deploy Documentation
        run: uv run --locked mkdocs gh-deploy --force
